dist: bionic
sudo: required
language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install autoconf automake autopoint libtool libpam0g-dev bison flex gettext
  - sudo apt-get install gcc
  - sudo apt-get install clang
  - sudo apt-get install musl musl-dev musl-tools
matrix:
  include:
    - name: "Build with gcc (dynamic)"
      os: linux
      env:
         - CC="gcc"
         - DISTCHECK_CONFIGURE_EXTRA_FLAGS=""
         - TRAVIS_CHECK_KEYWORDS='unittest e2e'
    - name: "Build with clang (dynamic)"
      os: linux
      env:
         - CC="clang"
         - DISTCHECK_CONFIGURE_EXTRA_FLAGS=""
         - TRAVIS_CHECK_KEYWORDS='unittest e2e'
    - name: "Build with musl (static)"
      os: linux
      env:
         # https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html
         #  -idirafter /usr/include/                  # Needed for Travis/Ubuntu build to pass, for linux/kd.h, etc.
         #  -idirafter /usr/include/x86_64-linux-gnu/ # Needed for Travis/Ubuntu build to pass, for asm/types.h
         - CC="musl-gcc -static -idirafter /usr/include/ -idirafter /usr/include/x86_64-linux-gnu/"
         - DISTCHECK_CONFIGURE_EXTRA_FLAGS="--disable-libkeymap --disable-vlock"
         - TRAVIS_CHECK_KEYWORDS='unittest'
script:
  - ./tests/travis-ci-run
